apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels: {app: web}
spec:
  replicas: 3
  selector: {matchLabels:{app: web}}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata: {labels:{app: web}}
    spec:
      containers:
      - name: app
        image: ghcr.io/nginxdemos/hello:plain-text
        ports: [{containerPort: 80}]
        readinessProbe:
          httpGet: {path: /, port: 80}
          initialDelaySeconds: 2
        livenessProbe:
          httpGet: {path: /, port: 80}
          initialDelaySeconds: 10
        resources:
          requests: {cpu: "100m", memory: "128Mi"}
          limits:   {cpu: "500m", memory: "256Mi"}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels: {app: web}
spec:
  selector: {app: web}
  ports: [{port: 80, targetPort: 80}]